### ISSUE TITLE
"Fetching the value or values of a single named parameter" warning

### ISSUE THREAD

**Issue by maravento** [finisky/lightsquid-1.8.1#1]
ubuntu 22.04
apache 2.4.52
possible bug or a warning:

```
/etc/log/apache2/error.log
index.cgi: CGI::param called in list context from /var/www/html/lightsquid/index.cgi line 30, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 415.
```
there is a problem with this lines:
```
index.cgi:InitTPL("index",$co->param('tpl'));
bigfiles.cgi:InitTPL("bigfiles",$co->param('tpl'));
day_detail.cgi:InitTPL("day_detail",$co->param('tpl'));
get.cgi:CheckNewTPL($co->param('tpl'));
graph.cgi:    InitTPL("graph",$co->param('tpl'));
group_detail.cgi:InitTPL("group_detail",$co->param('tpl'));
month_detail.cgi:InitTPL("month_detail",$co->param('tpl'));
topsites.cgi:InitTPL("topsites",$co->param('tpl'));
user_detail.cgi:InitTPL("user_detail",$co->param('tpl'));
user_month.cgi:InitTPL("user_month",$co->param('tpl'));
user_time.cgi:InitTPL("user_time",$co->param('tpl'));
whousesite.cgi:InitTPL("whousesite",$co->param('tpl'));
```
how to solve? thanks

**Comment by maravento** [comment]
Proposal:
Just add to each line "scalar". example:
`InitTPL("index", scalar $co->param('tpl'));`
source: https://stackoverflow.com/a/32785777/8747573

**Comment by maravento** [comment]
waiting for confirmation if this proposal is the solution to the bug

**Comment by finisky** [comment]
> waiting for confirmation if this proposal is the solution to the bug

Seems that it's only a security warning for these lines. 

lightsquid is an ooooooooooold software which is out of maintenance for several years. Since I don't have the same environment to reproduce the issue, I'm not sure whether the proposal can fix the issue.

Just leave this issue open to provide hints for future users.

**Comment by maravento** [comment]
this warning floods the apache log. Applied the fix on all files containing `, scalar $co->param('tpl'));`  and the messages disappeared, but I'm not sure if that's the solution. hopefully some perl expert will weigh in on this thread.

![lightsquid-warning](https://user-images.githubusercontent.com/14880802/194718706-ce3690bf-4813-467d-bcb2-b3b5799f3f1a.png)

**Comment by maravento** [comment]
according to ChatGPT:

The error message refers to a Perl security warning that the `param()` method of the CGI library is being used in an unsafe manner. The warning suggests that `param()` be called in a scalar context, rather than a list context. To solve this problem, you must call `param()` in scalar context. Instead of calling `param()` on a list, make sure you call it on a scalar variable:
```
my $tpl = $co->param('tpl');
InitTPL("index", $tpl);
```
The other solution is the proposal. The `scalar` function converts the `param` method call to a scalar context, preventing it from being called in a list context and thus removing the security warning. So, by using `scalar $co->param('tpl')` as an argument to the `InitTPL` function, you are ensuring that the call to `param` is made in scalar context and removing the security warning.

It is important to note that the CGI library has been deprecated in Perl and it is recommended to use more modern and safer alternatives, such as Plack or PSGI.
